use_frameworks!

target 'GFLocalAuthentication_Example' do
  pod 'GFLocalAuthentication', :path => '../'

  target 'GFLocalAuthentication_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
